version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: portfolio/Dockerfile
    restart: always
    ports:
      - "3000:3000"
  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    restart: always
    ports:
      - "5000:5000"