version: '3'
services:
  frontend:
    build:
      context: ./portfolio
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"