version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Frontend
    restart: always
    ports:
      - "3000:3000"
  backend:
    build:
      context: .
      dockerfile: Backend
    restart: always
    ports:
      - "5000:5000"